import type { EmailTemplate } from '@/services/settings/email-template.types'

export const EMAIL_TEMPLATES: EmailTemplate[] = [
  {
    id: 'activation-code',
    name: 'Activation code',
    description: 'Sent when a user needs to activate their account.',
    subject: 'Activate your fitematch account',
    preheader: 'Use your activation code to complete your registration.',
    body: 'Hi {{userName}}, your activation code is {{activationCode}}. This code expires soon.',
    variables: [
      {
        key: '{{userName}}',
        description: 'User full name',
      },
      {
        key: '{{activationCode}}',
        description: 'Activation code generated by the API',
      },
    ],
  },
  {
    id: 'company-approved',
    name: 'Company approved',
    description: 'Sent when a recruiter company is approved.',
    subject: 'Your company was approved',
    preheader: 'Your company can now publish jobs on fitematch.',
    body: 'Hi {{userName}}, {{companyName}} was approved. You can now create and publish job opportunities.',
    variables: [
      {
        key: '{{userName}}',
        description: 'Recruiter full name',
      },
      {
        key: '{{companyName}}',
        description: 'Approved company name',
      },
    ],
  },
  {
    id: 'company-rejected',
    name: 'Company rejected',
    description: 'Sent when a recruiter company is rejected.',
    subject: 'Your company review was not approved',
    preheader: 'Review the reason and update your company information.',
    body: 'Hi {{userName}}, {{companyName}} was not approved. Reason: {{reason}}.',
    variables: [
      {
        key: '{{userName}}',
        description: 'Recruiter full name',
      },
      {
        key: '{{companyName}}',
        description: 'Rejected company name',
      },
      {
        key: '{{reason}}',
        description: 'Rejection reason',
      },
    ],
  },
  {
    id: 'job-approved',
    name: 'Job approved',
    description: 'Sent when a job opportunity is approved.',
    subject: 'Your job was approved',
    preheader: 'Your job opportunity is ready on fitematch.',
    body: 'Hi {{userName}}, your job {{jobTitle}} was approved and can now receive applications.',
    variables: [
      {
        key: '{{userName}}',
        description: 'Recruiter full name',
      },
      {
        key: '{{jobTitle}}',
        description: 'Approved job title',
      },
    ],
  },
  {
    id: 'job-rejected',
    name: 'Job rejected',
    description: 'Sent when a job opportunity is rejected.',
    subject: 'Your job review was not approved',
    preheader: 'Review the reason and update your job opportunity.',
    body: 'Hi {{userName}}, your job {{jobTitle}} was not approved. Reason: {{reason}}.',
    variables: [
      {
        key: '{{userName}}',
        description: 'Recruiter full name',
      },
      {
        key: '{{jobTitle}}',
        description: 'Rejected job title',
      },
      {
        key: '{{reason}}',
        description: 'Rejection reason',
      },
    ],
  },
  {
    id: 'application-received',
    name: 'Application received',
    description: 'Sent when a candidate applies to a job.',
    subject: 'New application received',
    preheader: 'A candidate applied to one of your job opportunities.',
    body: 'Hi {{userName}}, {{candidateName}} applied to {{jobTitle}}.',
    variables: [
      {
        key: '{{userName}}',
        description: 'Recruiter full name',
      },
      {
        key: '{{candidateName}}',
        description: 'Candidate full name',
      },
      {
        key: '{{jobTitle}}',
        description: 'Job title',
      },
    ],
  },
  {
    id: 'application-status-updated',
    name: 'Application status updated',
    description: 'Sent when an application status changes.',
    subject: 'Your application status changed',
    preheader: 'There is an update about your application.',
    body: 'Hi {{userName}}, your application for {{jobTitle}} is now {{applicationStatus}}.',
    variables: [
      {
        key: '{{userName}}',
        description: 'Candidate full name',
      },
      {
        key: '{{jobTitle}}',
        description: 'Job title',
      },
      {
        key: '{{applicationStatus}}',
        description: 'Current application status',
      },
    ],
  },
]